spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/app_db
    username: appuser
    password: apppass
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

---
spring:
  config:
    activate:
      on-profile: local
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: k8s
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

