spring:
  application:
    name: internal-api-service
  datasource:
    url: jdbc:mariadb://localhost:3306/internal_api_db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000