spring:
  application:
    name: batch-service
  datasource:
    url: jdbc:mariadb://localhost:3307/batch_db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

# FeignClient URL 추가
internal:
  api:
    url: https://localhost:8080

external:
  api:
    url: https://localhost:8080